name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v1.0

    - uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        image: wearetherock/my-web
        tag: latest
        # registry: registry-url.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_PASSWORD }}
